apiVersion: v1
kind: Service
metadata:
  name: consul-server-external
  namespace: consul
spec:
  type: LoadBalancer
  selector:
    app: consul
    component: server
  ports:
    - name: grpc
      port: 8502
      targetPort: 8502
