global:
  name: consul
  datacenter: dc1
  peering:
    enabled: true
  tls:
    enabled: true
  acls:
    manageSystemACLs: true

server:
  replicas: 1
  extraConfig: |
    {"advertise_addr_wan": "48.206.145.6"}

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
  service:
    type: LoadBalancer
  wanAddress:
    source: "Service"
    port: 443
